baseURL: https://www.nataniel.me
languageCode: en-us
title: Nataniel Mendes - Fullstack Software Engineer & DevOps
theme: hugo-profile

outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - RSS

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    []
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: Nataniel Mendes - DevOps & Fullstack Cloud Architect
  description: Nataniel Mendes' Website
  # staticPath: ""  # The path to serve the static files from
  favicon: /fav.png

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    defaultTheme: light # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    # textColor:
    # secondaryTextColor:
    # backgroundColor:
    # secondaryBackgroundColor:
    primaryColor: '#0A5'
    # secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: Nataniel Mendes # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: Hi, my name is
    title: Nataniel.
    subtitle: I'm passionate about making companies deliver software
    content: I have a deep understanding of full-stack engineering, having started my career as a Full Stack Developer in 2014, and later incorporated DevOps expertise into my work routine in 2018. My capabilities encompass a broad spectrum of technical areas, ranging from Cloud Solutions Architecture and Backend Development to UI/UX design. I'm an end-to-end expert
    image: /images/profile.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: Resume
      url: https://drive.google.com/file/d/1V-zkx2B4eKvLNa6FryOGp8fAIQyVv20N/view?usp=sharing
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/natanielmendes
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/natanielcarvalho/?locale=en_US
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: About Me
    image: /images/me.jpg
    content: |-
      The term DevOps holds immense value to me as it reflects my expertise in both development and operations. After starting my journey as a Full Stack Developer in 2014, I integrated DevOps into my work routine in 2018. Since then, I have effectively deployed resources on AWS using Terraform, created CI/CD pipelines, and managed Kubernetes in production environments. By leveraging my development skills, I have successfully assisted countless developers in enhancing their operations experience and delivering superior software outcomes.
      Currently, I'm working on a project that promotes healthy and sustainable design practices, aiming to improve people's lives in the society.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - AWS
        - Terraform
        - Observability
        - CI/CD
        - Programming (Node.js, Go, Java, Kotlin, Typescript, Javascript, React)
        - Testing (Cypress, Selenium, Jest, Mocha, Chai, JUnit)
        - SQL and NoSQL databases (Oracle, MySQL, MongoDB, CouchDB)
        - Agile Methodologies (SCRUM, Kanban)

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: Senior Software Engineer
        company: GoAlto
        companyUrl: https://www.goalto.io/
        date: Nov 2021 - Now
        featuredLink:
          enable: true
          name: View the project
          url: https://www.goldenglobes.com/
        content: |
          - Defined architecture details with stakeholders, and mentored 7 peers over 4 highly accessed end-user-facing websites.
          - Improved GraphQL queries for Golden Globes, reducing page load time by 34%, and also configured fallback mechanisms.
          - Enhanced [Moola Market](https://moola.market/) API interaction efficiency by 37% through the implementation of robust error handling and log tracking mechanisms, leading to significantly improved overall performance.
          - Projects:
            - [Golden Globes](https://www.goldenglobes.com/)
            - [Moola Market](https://moola.market/)
            - [Fleeting](https://www.fleeting.us/)
            - [San Francisco App Works](https://www.sfappworks.com/)
          - Typescript / Javascript NodeJS + Express.js, and Go Backend Development.
          - Typescript / Javascript React 18+ with Redux and Angular 17+ Frontend, also using Gatsby for performance with Drupal as CMS.
          - Graphql, MongoDB, MySQL, as well as other SQL and NoSQL databases.
          - Jest, Mocha, Chai, and angular/core/testing applied to Unit and Integration Tests / Cypress for e2e testing.
          - Blockchain Technologies: Celo and Ethereum.
          - Continuous Integration and Deployment configuring pipelines on Jenkins with Docker + Compose, GitHub Actions, GitHub Pipelines, AWS, Kubernetes, Terraform, and Heroku.
          - REST API documentation using Swagger.
          - SCRUM Agile Methodology.

      - job: Senior Software Engineer
        company: TCS
        companyUrl: https://www.tcs.com/
        date: Sep 2019 - Nov 2021
        featuredLink:
          enable: false
        content: |
          - Discussed and modified many architectural details in 3 confidential global projects delivered to a Big 4 Company (70% of the team based in the US), integrating Google Suite, Splunk, and Azure Data Services.
          - [Innovation Pride Award](https://www.linkedin.com/in/natanielcarvalho/overlay/1614196961228/single-media-viewer/?profileId=ACoAAAm6cVUBgABHWxwPmyJxplRLW3pz-dG-gtU) received for continuous commitment to push the boundaries of creativity for a Big 4 & Fortune 500 global company by delivering a project in 11 months instead of 16.
          - NodeJS ES6+ and NestJS REST APIs Backend Development.
          - Angular 8+, React, and Vue.js Frontend Development.
          - MongoDB & Couchbase as NoSQL and Oracle & Postgres as SQL Databases.
          - Jest, Mocha, and Chai applied to E2E, Unit, and Integration Tests.
          - Queue management using Kafka.
          - SCRUM Agile Methodology.

      - job: Research & Development Engineer
        company: Kantar
        companyUrl: https://www.kantar.com/
        date: Jul 2018 - Set 2019
        featuredLink:
          enable: false
        content: |
          - Global-scale audience measurement project used in over 50 countries.
          - Heading up on requirements with Team Lead and Product Manager to refactor old APIs, replicating functionalities to backward-compatible NodeJS ES6+ APIs, while re-defining architecture details with stakeholders on new features in Nodejs for expanding and tuning MySQL.
          - Backend and Frontend development using NodeJS ES6+ APIs and AngularJS.
          - Several NodeJS APIs deployed on Linux docker containers and RHEL servers using NGINX docker container as a reverse proxy.
          - Persistence using MySQL database.
          - TDD with Jest applied to Unit and Integration Tests.
          - SCRUM agile methodology.
          - CI/CD configuring pipelines on Jenkins with Docker.

      - job: Co-Founder
        company: O-Blue - Blockchain for Business
        companyUrl: https://www.linkedin.com/company/o-blue/about/
        date: Dec 2017 - Oct 2018
        info:
          enable: false
        featuredLink:
          enable: true
          name: View the project
          url: https://88iseguradora.digital/
        content: |
          In pursuit of my entrepreneurial goals, I co-founded a startup that provided innovative blockchain-based business solutions. We specialized in:
          - [Hyperledger Fabric](https://www.hyperledger.org/use/fabric)
          - [R3 Corda](https://r3.com/products/corda/)
          - Continuous Integration / Delivery in AWS
          - Node.JS, Java, Kotlin, and Symfony (PHP) Backend
          - React with Redux Frontend Development

          Successfully delivered 2 projects to clients:
          - [CertDox](https://certdox.com.br/) (Blockchain-based platform provides secure document notarization services.).
          - [88i](https://88iseguradora.digital/) (Platform that leverages smart contracts to facilitate seamless business logic among multiple parties including customers, insurance providers, re-insurance companies, and gadget maintenance service providers.).

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: Bachelor's degree in Information Systems
        school:
          name: Mackenzie 1870
          url: https://www.mackenzie.br/universidade
        date: 2014 - 2018
        GPA: 3.9 out of 5.0
      - title: C1 English Level - Gold Coast Intensive English Program
        school:
          name: BROWNS English Language School
          url: https://brownsenglish.edu.au/
        date: 2016 - 2017
        GPA: 98% success rate

  # Achievements
  achievements:
    enable: true
    title: Certifications
    items:
      - title: Certified Kubernetes Application Developer (CKAD)
        content: The Linux Foundation
        url: https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/284f88a2-4998-5410-b723-0e13a19ddd00-nataniel-mendes-de-carvalho-neto-certified-kubernetes-application-developer-ckad-certificate.pdf
      - title: Innovation Pride Award
        content: Innovation Pride Award received for continuous commitment to push the boundaries of creativity for a project delivered to a Big 4 & Fortune 500 global company.
        url: https://www.linkedin.com/in/natanielcarvalho/overlay/1614196961228/single-media-viewer/?profileId=ACoAAAm6cVUBgABHWxwPmyJxplRLW3pz-dG-gtU
      - title: Professional Scrum Master I
        content: Scrum.org
        url: https://www.scrum.org/user/498760
      - title: Corda Certified Developer (Distributed Ledger Technology)
        content: R3
        url: https://www.credly.com/badges/a392418f-0e92-40d6-a95d-1f2ffd94965f/linked_in_profile
      - title: Blockchain Foundation Developer
        content: IBM
        url: https://www.credly.com/badges/83964a36-b2ca-436c-8638-d8795c771251/linked_in_profile

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Golden Globe Awards
        content: Annual ceremony that honors the best achievements in film and television, both domestic and foreign. The event is organized by the Hollywood Foreign Press Association (HFPA) and typically takes place in January. The ceremony is widely viewed as a precursor to the Academy Awards, and it attracts a star-studded audience of celebrities and industry professionals from around the world. Awards are presented in various categories, including Best Picture, Best Director, Best Actor, Best Actress, Best Television Series, and more.
        image: /images/projects/gg-trophy-logo-2x.png
        featured:
          name: Visit Page
          link: https://www.goldenglobes.com/
        badges:
          - React
          - Gatsby
          - Node.js
          - Jest
          - Graphql
          - Drupal
          - Javascript
          - SCSS
        # links
        #   - icon: fa fa-envelope
        #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile
        #   - icon: fab fa-twitter
        #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Moola Market
        content: Moola Market is an online platform that connects borrowers with a network of individual lenders. The platform specializes in providing short-term loans to individuals and small businesses, offering fast and easy access to cash when needed. Borrowers can apply for loans ranging from $500 to $10,000, with repayment terms ranging from three to 36 months. The platform uses a proprietary underwriting model that takes into account various factors, such as credit score, income, and employment history, to determine the borrower's eligibility and loan terms. Investors on the platform can browse and invest in loan opportunities, earning interest on their investments over the loan term. Moola Market offers a user-friendly interface and provides reliable customer support to both borrowers and investors.
        image: /images/projects/moola-market.jpeg
        featured:
          name: Visit Platform
          link: https://moola.market/
        badges:
          - React
          - Node.js
          - Javascript
          - SASS / SCSS
          - CI/CD
          - Jenkins
        links:
          - icon: fab fa-github
            url: https://github.com/moolamarket

      - title: Fleeting
        content: Fleeting is an online platform that provides trucking companies with access to a network of on-demand drivers. The platform helps trucking companies to optimize their asset utilization by providing a flexible and scalable solution for driver staffing. Fleeting offers a user-friendly interface that allows trucking companies to post jobs, view driver profiles, and manage driver assignments in real-time. Drivers on the platform can create a profile, set their own rates, and accept jobs based on their availability. Fleeting provides a comprehensive insurance policy that covers drivers while they are on the job, ensuring that both the driver and the trucking company are protected. The platform offers a simple and cost-effective solution for trucking companies to manage their driver staffing needs and for drivers to find new opportunities to earn income.
        image: /images/projects/fleeting.jpeg
        featured:
          name: Visit Page
          link: https://www.fleeting.us/
        badges:
          - Jenkins
          - CI/CD
          - Node.js
          - React
          - Jest
          - Typescript
          - Javascript
          - SASS / SCSS

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: natanielmendes@hotmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: blogs
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/natanielmendes
      linkedin: https://www.linkedin.com/in/natanielcarvalho/?locale=en_US

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: min read
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: Read
    toc: Table Of Contents
    copyright: All rights reserved
    pageNotFound: Page not found
    emailText: Check out this site

  datesFormat:
    article: Jan 2, 2006
    articleList: Jan 2, 2006
    articleRecent: Jan 2, 2006
